namespace wakey
{
    [default_interface]
    runtimeclass KeepAwake : Windows.Foundation.IClosable
    {
        KeepAwake   (Microsoft.UI.Xaml.Window window);

        void Start  (Boolean bFirst);
        void Reload (void);
        void Stop   (void);
    }
}
